# Generated by Django 3.0.6 on 2020-10-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=100)),
                ('emp_age', models.PositiveIntegerField()),
                ('emp_salary', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
